/*******************************************************************************
 * Bayer AG
 * Study            : 21651 A double-blind, randomized, placebo-controlled
 *   multicenter study to investigate efficacy and safety of elinzanetant for
 *   the treatment of vasomotor symptoms over 26 weeks in postmenopausal women
 * Proj/Subst/GIAD  : 3427080 / BAY 3427080, ELINZANETANT BAY3427080 NK1-3 RA Vasomotor Symptoms
 *******************************************************************************
 *Name of program**************************************************************/
   %*LET prog = start;
/*
 * Purpose          : Set options and study specific macro variables.
 * Programming Spec :
 * Validation Level : 1 - Verification by Review
 * SAS Version      : Linux 9.4
 *******************************************************************************
 * Pre-conditions   :
 * Post-conditions  :
 * Comments         :
 *******************************************************************************
 * Author(s)        : egavb (Reema S Pawar) / date: 10SEP2023
 * Reference prog   : /var/swan/root/bhc/3427080/21652/stat/main01/val/analysis/pgms/start.sas (eokcw (Vijesh Shrivastava) / date: 28SEP2022)
 ******************************************************************************/

/* To make sure that study is run with the SAS version programs were developed for.  */
%checksasver(version = 9.4);

%LET v_standard = std_dali;
%LET project = &compound.;

*this is to include the Compound codelists;
%assignMetaLibs4SWAN(
    level_area                 = C_PROD G_PROD
  , compoundStandardFolderName = std_dali
  , adam_ig_v                  = 1.1
  , sdtm_ig_v                  = 3.2
  , datamodel                  = DALI
);




%LET eva_param_extend_rule = ;

*reset codelist library to reflect new ADS2 world.;
LIBNAME codelist (codelist ADSC_C_P);

*Assign thesauri codelist and libs;
%assignThesauri(tsdat = sp.ts)


%*Get Drug groupings for Prohibited medications;
LIBNAME WHODDSDG "/var/swan/root/bhc/thesauri/whodd/%lowcase(&v_whodd.)/data/drug_groupings/"  ACCESS = READONLY;


/*< Macro variable for result file name */

%GLOBAL reportno;
%LET reportno= PH - 42782;



%GLOBAL resultPrefix;
%LET resultPrefix= &study._ph42782_;


/*< Macro variables for Treatment arm for table display */
%GLOBAL treat_arm_a treat_arm_p treat_arm_fmt;
%LET treat_arm_a = trt01an;
%LET treat_arm_p = trt01pn;
%LET treat_arm_fmt = z_trt.;

/* avoid message like "ERROR: Template 'Pharma' was unable to write to template store!" */
/* which happen when I have multiple Sas-Sessions open and multiple Sas-runs which uses the Template store*/
ODS PATH work.templat(update) sasuser.templat(read) sashelp.tmplmst(read);

******************************************************************************;
*< General options;
******************************************************************************;

***************************************************************************;
*** Set here the papersize for the rtf output in mosto;
*** For US it is LETTER for all other it is A4
***************************************************************************;
*? Change A4 to LETTER if needed;
%GLOBAL papersize;  *<-; %LET papersize = A4;
OPTION PAPERSIZE = &papersize;

**** For macro iniprog. Sets whether output/log is routed to files or not.;
**** The latter is needed for program development and debugging;
**** Parameters DO NOT need to be switched to Y(ES) for Prod runs! This is handled automatically;
%GLOBAL default_print2file;     *<-; %LET default_print2file  = n;
%GLOBAL default_log2file;       *<-; %LET default_log2file    = y;
%GLOBAL default_createRTF;      *<-; %LET default_createRTF   = N; *if you use poster the ini_prog will set it to Y;

* Pagesize (ps) and linesize (ls) for lst output;
%GLOBAL ps;     *<-; %LET ps=51;
%GLOBAL ls;     *<-; %LET ls=133;


OPTIONS
       source2              /* writes secondary source statements from included files to the SAS log */
       nomprint             /* Specifies whether SAS statements generated by macro execution are traced for debugging. */
       nocenter             /* Specifies whether to center or left align SAS procedure output. */
       nobyline             /* Specifies whether to print BY lines above each BY group. */
       pagesize=&ps.        /* Specifies the number of lines that compose a page of SAS output. */
       linesize=&ls.        /* Specifies the line size of SAS Log and Output windows. */
       missing =.           /* Specifies the character to print for missing numeric values. */
       lrecl=1024           /* Specifies the default logical record length to use for reading and writing external files. */
       ;

*<###########################################################################################;
*< Study/Pool specific settings start here                                                   ;
*<###########################################################################################;

**********************************************;
* Subject definition;
**********************************************;
%GLOBAL subj_var;       *<-; %LET subj_var = USUBJID;
%GLOBAL subj_label;     *<-; %LET subj_label = subject;            * <Quote from GCat: The word <Subjects> will be used instead of Patients, Volunteers, etc.>;
%GLOBAL rand_label;     *<-; %LET rand_label = (all randomized &subj_label.s);


**********************************************;
* Populations;
**********************************************;
%GLOBAL los_label;      *<-; %LET los_label   = (listing only set);
%GLOBAL los_cond;       *<-; %LET los_cond    = LOSFL EQ 'Y';
%GLOBAL saf_label;      *<-; %LET saf_label   = (safety analysis set);
%GLOBAL saf_cond;       *<-; %LET saf_cond    = SAFFL EQ 'Y';
%GLOBAL fas_label;      *<-; %LET fas_label   = (full analysis set);
%GLOBAL fas_cond;       *<-; %LET fas_cond    = FASFL EQ 'Y';
%GLOBAL itt_label;      *<-; %LET itt_label   = (intent to treat set);
%GLOBAL itt_cond;       *<-; %LET itt_cond    = ITTFL EQ 'Y';
%GLOBAL pps_label;      *<-; %LET pps_label   = (per protocol set);
%GLOBAL pps_cond;       *<-; %LET pps_cond    = PPROTFL EQ 'Y';
%GLOBAL pk_label;       *<-; %LET pk_label    = (pharmacokinetic analysis set);
%GLOBAL pk_cond;        *<-; %LET pk_cond     = PKFL EQ 'Y';
%GLOBAL pk1_cond;       *<-; %LET pk_cond     = PK1FL EQ 'Y';
%GLOBAL pkact_label;    *<-; %LET pkact_label = %str((pharmacokinetic analysis set, &subj_label.s under active substance));
%GLOBAL pd_label;       *<-; %LET pd_label    = (pharmacodynamic analysis set);
%GLOBAL pd_cond;        *<-; %LET pd_cond     = PDFL EQ 'Y';
%GLOBAL pdact_label;    *<-; %LET pdact_label = %str((pharmacodynamic analysis set, &subj_label.s under active substance));
%GLOBAL enr_label;      *<-; %LET enr_label   = (all enrolled subjects);
%GLOBAL enr_cond;       *<-; %LET enr_cond    = ENRLFL EQ 'Y';
%GLOBAL rand_cond;      *<-; %LET rand_cond   = RANDFL EQ 'Y';
%GLOBAL slas_label;     *<-; %LET slas_label  = (sleep analysis set);
%GLOBAL slas_cond;      *<-; %LET slas_cond   = SLASFL EQ 'Y';

%GLOBAL fas_wk26_label;      *<-; %LET fas_wk26_label   = for subjects on treatment at week 26 visit (full analysis set);
%GLOBAL fas_wk26_cond;       *<-; %LET fas_wk26_cond    = FASFL EQ 'Y' and ONT26FL EQ 'Y';

/* Note: a population string is not applicable according Global Standard Listings Catalog V1.13 */
%GLOBAL sf_cond;        *<-; %LET sf_cond     = scrnflfn EQ 'Y';


**********************************************;
* Treatment;
**********************************************;
%GLOBAL treat_var;              *<-; %LET treat_var                  = TRT01AN;     * or TRT##PN or TRT##AN, check study SAP;
%GLOBAL treat_var_listings_part;*<-; %LET treat_var_listings_part    = TRT01PN;     * or TRT##PN;
                                                                                    * According Global Standard Listings Catalog V1.13,
                                                                                    * Planned treatment is used for all listings;
                                                                                    * for non-CP studies.  For CP studies, Actual treatment is presented in the listings.;
%GLOBAL treat_seq;              *<-; %LET treat_seq                  = TRTSEQAN;    * or TRTSEQPN;

**********************************************;
* Subgroups;
**********************************************;
%GLOBAL subgroup_vars;
%LET subgroup_vars = APTHINDX SEX RACEGR1N REGION1N WTGRPN AGEGR1N BMIGRPN EGFRGRPN STRKHXFL EIASSTK CAASVI CKDHXFL CADHXFL HIBPHXFL DIABHXFL OBIBL HMTRMRI DWIP TMBEDTFL SMOKHXN NIHSSCRN MRSSCR7N TTIERANN STRSBTPN;

******************************************************************************;
*< MoSTO version 6 global parameters;
******************************************************************************;

%* recommended settings;
%GLOBAL mosto_param_emptytxt_new;   *<-; %LET mosto_param_emptytxt_new  = yes;   * Datalist: indicator to use new or old text for empty tables ;
%GLOBAL mosto_param_hsplit_new;     *<-; %LET mosto_param_hsplit_new    = yes;   * Datalist: hsplit then works together with maxlen /bylen ;
%GLOBAL mosto_param_data_n_hsplit;  *<-; %LET mosto_param_data_n_hsplit = yes;   * Datalist: option to use hsplit character after label and big-n ;
%GLOBAL mosto_param_triggerwarn;    *<-; %LET mosto_param_triggerwarn   = yes;   * Incidence_calc: indicator to warn when no triggercond is used ;


%* optional general settings;
%* Order of treatmgr according to Global Standards of Data Displays;
%GLOBAL mosto_param_class;          *<-; %LET mosto_param_class         = &treat_var.;
%GLOBAL mosto_param_class_order;    *<-; %LET mosto_param_class_order   = 100 101;  * <Quote from Data Display Guide: Order of doses: Highest (first) to lowest of BSP treatments then placebo and/or control drug.>;
%GLOBAL mosto_param_order_var;      *<-; %LET mosto_param_order_var     = &treat_var. = &mosto_param_class_order.;

*setting for trtgrp;
%GLOBAL trtgrp_param_class;         *<-; %LET trtgrp_param_class         = trtgrp;
%GLOBAL trtgrp_param_class_order;   *<-; %LET trtgrp_param_class_order   = 100 101;  * <Quote from Data Display Guide: Order of doses: Highest (first) to lowest of BSP treatments then placebo and/or control drug.>;
%GLOBAL trtgrp_param_order_var;     *<-; %LET trtgrp_param_order_var     = trtgrp;


**********************************************;
* Dockfish property file;
**********************************************;
%GLOBAL properties;              *<-;

%LET properties                  = &PRGDIR/docfish.properties;     * property file containing dockfish file property;


**********************************************;
* Super script code for footnote  ;
**********************************************;
%GLOBAL super_a;  %LET super_a ={super ^{style [just=c fontsize=10pt font_face=arial]a}};
%GLOBAL super_b;  %LET super_b ={super ^{style [just=c fontsize=10pt font_face=arial]b}};
%GLOBAL super_c;  %LET super_c ={super ^{style [just=c fontsize=10pt font_face=arial]c}};
%GLOBAL super_d;  %LET super_d ={super ^{style [just=c fontsize=10pt font_face=arial]d}};
%GLOBAL super_e;  %LET super_e ={super ^{style [just=c fontsize=10pt font_face=arial]e}};
%GLOBAL super_f;  %LET super_f ={super ^{style [just=c fontsize=10pt font_face=arial]f}};
%GLOBAL super_g;  %LET super_g ={super ^{style [just=c fontsize=10pt font_face=arial]g}};

%GLOBAL s_a;  %LET s_a ={super ^{style[fontsize=10pt]a}};
%GLOBAL s_b;  %LET s_b ={super ^{style[fontsize=10pt]b}};
%GLOBAL s_c;  %LET s_c ={super ^{style[fontsize=10pt]c}};
%GLOBAL s_d;  %LET s_d ={super ^{style[fontsize=10pt]d}};
%GLOBAL s_e;  %LET s_e ={super ^{style[fontsize=10pt]e}};
%GLOBAL s_f;  %LET s_f ={super ^{style[fontsize=10pt]f}};
%GLOBAL s_g;  %LET s_g ={super ^{style[fontsize=10pt]g}};

%GLOBAL newline;  %LET newline = ^{newline};
